default_stages: [commit]
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      -   id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.14.0'
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint@>=5.16.0
        -   eslint-config-google@latest
